# Generated by Django 3.2.8 on 2021-10-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date recorded')),
                ('speed', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
